{
 "title": "Matura_01",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Heizung L1-3",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"fronius_data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n      r[\"_measurement\"] == \"power_data\" and\r\n      (r[\"_field\"] == \"ct_0_value\"))\r\n  |> aggregateWindow(every: (if int(v: v.windowPeriod) < int(v: 5s) then 5s else v.windowPeriod), fn: median)\r\n"
    }
   ]
  },
  {
   "title": "Heizung L1-3 Watt",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"fronius_data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n      r[\"_measurement\"] == \"power_data\" and\r\n      (r[\"_field\"] == \"ct_0_value\" or \r\n      r[\"_field\"] == \"Voltage_AC_Phase_1_Zaehler\"))\r\n  |> aggregateWindow(every: (if int(v: v.windowPeriod) < int(v: 5s) then 5s else v.windowPeriod), fn: median)\r\n"
    }
   ]
  },
  {
   "title": "Elektroauto L1",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"fronius_data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n      r[\"_measurement\"] == \"power_data\" and\r\n      (r[\"_field\"] == \"ct_1_value\"))\r\n  |> aggregateWindow(every: (if int(v: v.windowPeriod) < int(v: 5s) then 5s else v.windowPeriod), fn: median)\r\n"
    }
   ]
  },
  {
   "title": "Elektroauto L1 Watt",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"fronius_data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n      r[\"_measurement\"] == \"power_data\" and\r\n      (r[\"_field\"] == \"ct_1_value\" or\r\n      r[\"_field\"] == \"Voltage_AC_Phase_1_Zaehler\" or\r\n      r[\"_field\"] == \"PowerFactor_Phase_1\"))\r\n  |> aggregateWindow(every: (if int(v: v.windowPeriod) < int(v: 5s) then 5s else v.windowPeriod), fn: median)\r\n"
    }
   ]
  },
  {
   "title": "Zimmer Nils L3",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"fronius_data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n      r[\"_measurement\"] == \"power_data\" and\r\n      (r[\"_field\"] == \"ct_2_value\"))\r\n  |> aggregateWindow(every: (if int(v: v.windowPeriod) < int(v: 5s) then 5s else v.windowPeriod), fn: median)\r\n"
    }
   ]
  },
  {
   "title": "Zimmer Nils L3 Watt",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"fronius_data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n      r[\"_measurement\"] == \"power_data\" and\r\n      (r[\"_field\"] == \"ct_2_value\" or\r\n      r[\"_field\"] == \"Voltage_AC_Phase_3_Zaehler\" or\r\n      r[\"_field\"] == \"PowerFactor_Phase_3\"))\r\n  |> aggregateWindow(every: (if int(v: v.windowPeriod) < int(v: 5s) then 5s else v.windowPeriod), fn: median)\r\n"
    }
   ]
  },
  {
   "title": "Boiler L2",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"fronius_data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n      r[\"_measurement\"] == \"power_data\" and\r\n      (r[\"_field\"] == \"ct_3_value\"))\r\n  |> aggregateWindow(every: (if int(v: v.windowPeriod) < int(v: 5s) then 5s else v.windowPeriod), fn: median)\r\n"
    }
   ]
  },
  {
   "title": "Kalibrierung",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"fronius_data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n      r[\"_measurement\"] == \"power_data\" and\r\n      (r[\"_field\"] == \"ct_4_value\"or \r\n      r[\"_field\"] == \"Current_AC_Phase_2_Zaehler\"))\r\n  |> aggregateWindow(every: (if int(v: v.windowPeriod) < int(v: 5s) then 5s else v.windowPeriod), fn: median)\r\n"
    }
   ]
  },
  {
   "title": "Kühlschrank L3",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"fronius_data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n      r[\"_measurement\"] == \"power_data\" and\r\n      (r[\"_field\"] == \"ct_5_value\"))\r\n  |> aggregateWindow(every: (if int(v: v.windowPeriod) < int(v: 5s) then 5s else v.windowPeriod), fn: median)\r\n"
    }
   ]
  },
  {
   "title": "Wohnen+Küche L2",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"fronius_data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n      r[\"_measurement\"] == \"power_data\" and\r\n      (r[\"_field\"] == \"ct_6_value\"))\r\n  |> aggregateWindow(every: (if int(v: v.windowPeriod) < int(v: 5s) then 5s else v.windowPeriod), fn: median)\r\n"
    }
   ]
  },
  {
   "title": "Backofen L2",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"fronius_data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n      r[\"_measurement\"] == \"power_data\" and\r\n      (r[\"_field\"] == \"ct_7_value\"))\r\n  |> aggregateWindow(every: (if int(v: v.windowPeriod) < int(v: 5s) then 5s else v.windowPeriod), fn: median)\r\n"
    }
   ]
  },
  {
   "title": "Waschmaschine L1",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"fronius_data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n      r[\"_measurement\"] == \"power_data\" and\r\n      (r[\"_field\"] == \"ct_8_value\"))\r\n  |> aggregateWindow(every: (if int(v: v.windowPeriod) < int(v: 5s) then 5s else v.windowPeriod), fn: median)\r\n"
    }
   ]
  },
  {
   "title": "Ertrag Solar",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"fronius_data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n      r[\"_measurement\"] == \"power_data\" and\r\n      (r[\"_field\"] == \"Current_AC_Phase_1_Wechselrichter\" or\r\n       r[\"_field\"] == \"Current_AC_Phase_2_Wechselrichter\" or\r\n       r[\"_field\"] == \"Current_AC_Phase_3_Wechselrichter\"))\r\n  |> aggregateWindow(every: (if int(v: v.windowPeriod) < int(v: 5s) then 5s else v.windowPeriod), fn: median)\r\n"
    }
   ]
  },
  {
   "title": "Stromverbrauch Netz",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"fronius_data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n      r[\"_measurement\"] == \"power_data\" and\r\n      (r[\"_field\"] == \"Current_AC_Phase_1_Zaehler\" or\r\n       r[\"_field\"] == \"Current_AC_Phase_2_Zaehler\" or\r\n       r[\"_field\"] == \"Current_AC_Phase_3_Zaehler\"))\r\n  |> aggregateWindow(every: (if int(v: v.windowPeriod) < int(v: 5s) then 5s else v.windowPeriod), fn: median)\r\n"
    }
   ]
  },
  {
   "title": "Stromverbrauch Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"fronius_data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n      r[\"_measurement\"] == \"power_data\" and\r\n      (r[\"_field\"] == \"Current_AC_Phase_1_Wechselrichter\" or\r\n       r[\"_field\"] == \"Current_AC_Phase_2_Wechselrichter\" or\r\n       r[\"_field\"] == \"Current_AC_Phase_1_Zaehler\" or\r\n       r[\"_field\"] == \"Current_AC_Phase_2_Zaehler\" or\r\n       r[\"_field\"] == \"Current_AC_Phase_3_Zaehler\" or\r\n       r[\"_field\"] == \"Current_AC_Phase_3_Wechselrichter\"))\r\n  |> aggregateWindow(every: (if int(v: v.windowPeriod) < int(v: 5s) then 5s else v.windowPeriod), fn: median)\r\n"
    }
   ]
  }
 ]
}